POST http://localhost:3000/api/services
Content-type: application/json

{
    "name": "Algum serviço 2",
    "description": "Qualquer descrição",
    "price":1900,
    "image": "https://images.pexels.com/photos/7478450/pexels-photo-7478450.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/65da8b306b207279d906c6b6

###
DELETE http://localhost:3000/api/services/65da8b306b207279d906c6b6

###
PUT http://localhost:3000/api/services/65da8bf96b207279d906c6b6
Content-type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "Qualquer descrição",
    "price":2300,
    "image": "https://images.pexels.com/photos/7478450/pexels-photo-7478450.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}